apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: devopsrumee/food-delivery-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: JWT_SECRET
          value: "tomato123secret"
        - name: SALT
          value: "10"
        - name: MONGO_URL
          value: "mongodb+srv://admin:admin@cluster0.pk8uire.mongodb.net/food-delivery"
        - name: STRIPE_SECRET_KEY
          value: "your_stripe_key"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 4000
    targetPort: 4000
  type: LoadBalancer
